required = [
  "github.com/golang/protobuf/protoc-gen-go",
  "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway",
  "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger",
  "github.com/infobloxopen/protoc-gen-gorm"
]

[prune]
  go-tests = true
  unused-packages = true
